import React, { useEffect, useState } from 'react'
import { useAppData } from '../context'
import { saveEvent } from '../lib/dataService'

export default function SettingsPanel(){
  const { event }=useAppData(); const [form,setForm]=useState(event||{}); const [saved,setSaved]=useState(false); const [busy,setBusy]=useState(false)
  useEffect(()=>{if(event)setForm(event)},[event])
  async function submit(e){e.preventDefault();setBusy(true);setSaved(false);try{const {id,...payload}=form;await saveEvent(payload);setSaved(true)}finally{setBusy(false)}}
  return <div className="admin-panel"><div className="admin-panel-title"><div><span className="eyebrow">Event setup</span><h1>Event settings</h1><p>Edit the attendee-facing event information.</p></div></div><form className="settings-form admin-card" onSubmit={submit}><div className="form-grid"><label>Event name<input value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Organiser<input value={form.organiser||''} onChange={e=>setForm({...form,organiser:e.target.value})}/></label><label className="span-2">Tagline<input value={form.tagline||''} onChange={e=>setForm({...form,tagline:e.target.value})}/></label><label>Date<input type="date" value={form.date||''} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Venue<input value={form.venue||''} onChange={e=>setForm({...form,venue:e.target.value})}/></label><label className="span-2">Venue note<input value={form.locationNote||''} onChange={e=>setForm({...form,locationNote:e.target.value})}/></label><label>Hashtag<input value={form.hashtag||''} onChange={e=>setForm({...form,hashtag:e.target.value})}/></label><label>Event status<select value={form.eventStatus||'live'} onChange={e=>setForm({...form,eventStatus:e.target.value})}><option value="upcoming">Upcoming</option><option value="live">Live</option><option value="ended">Ended</option></select></label><label>Wi-Fi name<input value={form.wifiName||''} onChange={e=>setForm({...form,wifiName:e.target.value})}/></label><label>Wi-Fi password<input value={form.wifiPassword||''} onChange={e=>setForm({...form,wifiPassword:e.target.value})}/></label><label>Contact name<input value={form.contactName||''} onChange={e=>setForm({...form,contactName:e.target.value})}/></label><label>Contact phone<input value={form.contactPhone||''} onChange={e=>setForm({...form,contactPhone:e.target.value})}/></label><label>Contact email<input type="email" value={form.contactEmail||''} onChange={e=>setForm({...form,contactEmail:e.target.value})}/></label><label>Website<input type="url" value={form.websiteUrl||''} onChange={e=>setForm({...form,websiteUrl:e.target.value})}/></label><label className="span-2">Welcome message<textarea rows="4" value={form.welcomeMessage||''} onChange={e=>setForm({...form,welcomeMessage:e.target.value})}/></label></div><div className="settings-actions">{saved&&<span className="success-text">Changes saved.</span>}<button className="btn btn-black" disabled={busy}>{busy?'Saving…':'Save settings'}</button></div></form></div>
}
